### ISSUE TITLE
Re-run pipelines with updated platemap

### ISSUE THREAD

**Issue by gwaybio** [WayScience/NF1_SchwannCell_data#18]
In #17 @jenna-tomkinson modified the platemap file. We should take care to rerun all impacted modules following the platemap update.

I am adding this issue to make sure we do this.

**Comment by jenna-tomkinson** [comment]
@gwaybio 

All modules that needed the metadata updated (e.g. DeepProfiler processing and Pycytominer processing of the CellProfiler features) have been rerun with the correct genotypes (e.g WT and Null).
