### ISSUE TITLE
Open data access

### ISSUE THREAD

**Issue by gwaybio** [WayScience/NF1_SchwannCell_data#4]
Hi @jenna-tomkinson - let's make the data public.

I've reviewed the agreement and there is nothing binding on the timing of data release or the nature of our analyses (as long as we perform our statement of work!). Releasing the data now makes it a bunch easier for us to analyze it in multiple ways.

Can you let me know how big the data are? This will help us to decide _where_ to put it.

**Comment by jenna-tomkinson** [comment]
Hi @gwaybio,

Glad to hear we can make the data public!

The "Imaging Pilots" (96 images) that we have total up to 212.9 MB. Based on that, I think that we can put the images on GitHub or Github LFS. 

Let me know which one we should proceed with.

**Comment by gwaybio** [comment]
Sounds good. thanks for reporting the size!

Let's go with base github for now (we can always move to LFS later).

I checked back in with dvc, and [it doesn't look like they've added additional file support](https://dvc.org/doc/command-reference/remote/add). OneDrive or Dropbox would have worked particularly well for us. If our data were much bigger, it would have been worth exploring other dvc remotes, but not for 200MBs.

We're likely to have bigger data in the future, and for this we'd either have an IDR or Figshare depositing step. (see https://www.waysciencelab.com/2022/06/01/datastrategy.html)

Can you add the data in a separate PR? (data should belong in a `0.data_download` folder I think)

**Comment by jenna-tomkinson** [comment]
@gwaybio How would this module work with Dropbox? I noticed that the lab uses Aspera (Mitocheck) and Docker (Cell-Health). Are these what I should use in this module?

**Comment by gwaybio** [comment]
good question! (and this issue is a perfect place to ask).

We don't need any of those solutions (Dropbox, Aspera, Docker) for this repo.

The data are small enough **that you can include them in a folder directly in this repository**. Does that make sense?

**Comment by gwaybio** [comment]
(i.e. we'll continue to use dropbox as a data backup solution)

**Comment by jenna-tomkinson** [comment]
That makes perfect sense! It seemed way too easy in comparison. I will get those pilot images up!

**Comment by gwaybio** [comment]
👍 we like easy solutions!
